HYDlgn.jobweb/Controllers/SettingController.cs
using BootstrapTable.Pager;
using HYDlgn.Abstraction;
using HYDlgn.Framework.AppModel;
using HYDlgn.Framework.Model;
using HYDlgn.Framework.Tools;
using HYDlgn.jobweb.AppModels;
using HYDlgn.jobweb.Service;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HYDlgn.jobweb.Controllers
{
    public class SettingController : BaseController
    {
        [JWTAuth(level =0)]
        [HttpGet]
        public ActionResult Edit(string id)
        {
            ViewBag.ContentWidth = "";
            ViewBag.EditTitle = "Maximum No. of Cars available";
            var editsetting = _db.CoreSettings.FirstOrDefault(e => e.SettingId == id);
            var model = editsetting.MapTo(new EditSettingModel());

            return View(model);
        }

        [JWTAuth(level =0)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditSettingModel model)
        {
            

            return Redirect("/Setting");
        }


        // GET: Setting
        [JWTAuth(level =0)]
        [HttpGet]
        public ActionResult Index()
        {
            return Index(new QySettingModel());
        }
        [HttpPost]
        [JWTAuth(level = 0)]
        [ValidateAntiForgeryToken]
        public ActionResult Index(QySettingModel query)
        {
            ViewBag.ContentWidth = "";
            List<EditSettingModel> settings = new List<EditSettingModel>();
            _db.CoreSettings.Where(e => e.CanEdit).ToList().ForEach(setting =>
            {
                var model = setting.MapTo(new EditSettingModel());
                settings.Add(model);
            });
            if(!string.IsNullOrEmpty(query.AskCommon))
            {
                query.AskCommon = query.AskCommon.ToLower();
                settings = settings.Where(e => e.SettingId.ToLower().Contains(query.AskCommon)).ToList();
            }
            var dict = new List<JSort>();
            if(!string.IsNullOrEmpty(query.sort))
            {
                var sort = new JSort { Order = query.sort.EndsWith("+") ? "asc" : "desc", Column = query.sort.Substring(0, query.sort.Length - 1) };
                dict.Add(sort);

            }
            query.totalRecords = settings.Count;
            if ((query.page - 1) * 10 > query.totalRecords)
            {
                query.page = query.totalRecords / 10;
            }
            query.Records = settings.BuildOrderBys(JSONtoDynamicHelper.SaveDictionaryToJSON(dict)).ToPagerList(query.page);
            return View(query);
        }
    }
}

HYDlgn.jobweb/Views/Setting/Edit.cshtml
@model HYDlgn.Framework.AppModel.EditSettingModel
@using HYDlgn.jobweb.Tools
@{
    var minValue = int.Parse(Model.SettingValue);

}
<main>
    <div class="ribbon"></div>
    <div class="card-container">
        <div class="mdc-card">
            @using (Html.BeginForm("Edit", "Setting", FormMethod.Post, htmlAttributes: new { @class = "content-grid content-grid--active" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(e=> e.Id)
                @Html.HiddenFor(e => e.SettingId)
                <div class="mdc-layout-grid">
                    <div class="mdc-layout-grid__inner">
                        <div class="mdc-layout-grid__cell--span-4-phone mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-12-desktop">
                            <h2>@ViewBag.EditTitle</h2>
                        </div>
                        @Html.GetNumber(e=> e.SettingValue,1,true,minValue,5)
                    </div>
                </div>
                <div class="mdc-layout-grid">
                    <div class="mdc-layout-grid__inner">
                        <div class="mdc-layout-grid__cell--span-4-phone mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-12-desktop">
                            <input type="submit" class="rkmd-btn btn-red mdc-button mdc-button--raised mdc-button--secondary"
                                   value="Save" />
                            <a color="secondary"
                               class="draft-btn rkmd-btn btn-grey mdc-button mdc-button--raised mdc-button--leading"
                               href="@Url.Action("Index","Setting")">
                                <span class="mdc-button__ripple"></span>
                                <i class="material-icons mdc-button__icon" aria-hidden="true">cancel</i>
                                <span class="mdc-button__label">Cancel</span>
                            </a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</main>
@section Scripts {

    @Scripts.Render("~/bundles/theme")
    <script type="text/javascript" src="@Url.Content("~/Scripts/theme.util.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/my.settingedit.js")"></script>

}

@section styles {
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.matter.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.material.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.matter-select.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.matter-check.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.matter-btn.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.bootstrap.date.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.misc.css")" />



}

HYDlgn.jobweb/Views/Setting/Index.cshtml
@using HYDlgn.jobweb.AppModels
@using BootstrapTable.Pager.Mvc
@using BootstrapTable.Pager
@using HYDlgn.jobweb.Tools
@using HYDlgn.Abstraction
@using HYDlgn.Framework.AppModel
@model QySettingModel
@{
    ViewBag.Title = "Setting List";
    var UserLevel = HttpContext.Current.Session[Constants.Session.UserLevel]?.ToString() ?? "";
    var isAdmin = HttpContext.Current.Session[Constants.Session.IsAdmin] != null && (bool)HttpContext.Current.Session[Constants.Session.IsAdmin];
    var userLevelvalue = 99999;
    var isPower = false;

    if (!string.IsNullOrEmpty(UserLevel) && int.TryParse(UserLevel, out userLevelvalue))
    {
        userLevelvalue = int.Parse(UserLevel);
        isPower = userLevelvalue < 18;

    }
    else
    {
        userLevelvalue = 99999;
    }

}
<h2>
    @ViewBag.Title
    <div class="pull-right">
        <a id="btnnew" class="search-btn matter-button-contained btn-yellow hidden" href="@Url.Action("Edit","Setting")">Setting New</a>
    </div>
</h2>
<form id="genDriverList" action="@Url.Action("Index")" method="post">
    @Html.AntiForgeryToken()
    <div class="search-container">
        <div class="row pt-10 d-fx">
            <div class="col-sm-5">
                @Html.GetUnderline(m => m.AskCommon, anyclaasses: "asklarger")
                @Html.HiddenFor(m => m.page, htmlAttributes: new { @class = "page-val" })
                @Html.HiddenFor(m => m.sort, new { @class = "sort-val" })
            </div>
            <div class="col-sm-3 middle">
                <input type="submit" value="Filter" class="search-btn matter-button-contained btn-grey" />
            </div>
        </div>
    </div>
</form>
<div style="max-width:700px">
    <table class="table" style="table-layout:fixed">

        <colgroup>
            <col style="width:10px">
            <col style="width:150px">
            <col style="width:300px">
            <col style="width:10%">
        </colgroup>
        <thead>
            <tr>
                <th>
                    <input id="checkAll" type="checkbox" disabled class="hidden" />
                </th>
                <th class="sort-SettingId" sort>
                    @Html.DisplayNameFor(model => model.ColumnSettingId)
                </th>
                <th class="sort-SettingValue" sort>
                    @Html.DisplayNameFor(model => model.ColumnSettingValue)
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (EditSettingModel item in Model.Records)
            {
                <tr>
                    <td class="col-checkbox">
                        @Html.HiddenFor(modelItem => item.SettingId, new { @class = "gen-id" })
                    </td>
                    <td class="middle col-settingid">
                        @Html.DisplayFor(modelItem => item.SettingId)
                    </td>
                    <td class="middle col-settingvalue">
                        @Html.DisplayFor(modelItem => item.SettingValue)
                    </td>
                    <td class="middle col-buttons">
                        <a class="btn btn-crimson thinner" href="@Url.Action("Edit", new { Id= item.SettingId})">Edit</a>

                    </td>

                </tr>
            }
        </tbody>

    </table>
</div>

<div>
    Total Count:<span>@Model.totalRecords</span>
</div>
@Html.Pager((IPager)Model.Records, page => Url.Action("Index", new { page }), new PagerOptions { TextToPreviousPage = "<i class='fa fa-step-backward'></i>", TextToNextPage = "<i class='fa fa-step-forward'></i>", TextToFirstPage = "<i class='fa fa-fast-backward'></i>", TextToLastPage = "<i class='fa fa-fast-forward'></i>" })


@section Scripts {
    @Scripts.Render("~/bundles/theme")
    <script type="text/javascript" src="@Url.Content("~/Scripts/theme.util.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/my.settinglist.js")"></script>
}

@section styles {
    <link rel="stylesheet" href="@Url.Content("~/Content/util.underline.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.matter.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.material.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.matter-check.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/theme.misc.css")" />



    <style>
        .no-top {
            padding-top: 0px !important;
        }

        .asklarger label {
            font-size: 1.4rem !important;
        }

        .label-showlarger {
            font-size: 16px;
            margin-bottom: -0.2rem !important;
        }
    </style>
}